add eslint.yml
siotomo/girls pull request #25
Opened 2022-12-11 11:42 UTC by acropolicejp

## 概要

## 参考URL

2022-12-13 10:56 UTC, siotomo requested changes
もし参考にした記事があったら載っけておいてもらえると嬉しいですー

2022-12-13 10:56 UTC, siotomo commented on .github/workflows/eslint.yml
> +          eslint_flags: app/frontend/js/
これ必要ない気がします。

2022-12-13 13:22 UTC, acropolicejp commented on .github/workflows/eslint.yml
> +          eslint_flags: app/frontend/js/
webpack.config.jsとかにもLint走って大変なのでつけたいです

2022-12-13 13:31 UTC, siotomo commented on .github/workflows/eslint.yml
> +          eslint_flags: app/frontend/js/
.eslintrcで制御できませんか？

2022-12-25 07:50 UTC, siotomo approved these changes

2022-12-25 07:50 UTC, merged